import { reactive } from 'vue'

export const widgetStore = reactive({
  widgets: [
    {
        uid: null,
        name: 'Text',
        icon: 'bi bi-textarea-t',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Background: "",
          Color: "",
          Align: 'left',
          FontSize: null,
          FontSizeType: { name: 'rem', code: 'rem' },
          LineHeight: null,
          LineHeightType: { name: 'rem', code: 'rem' },
        },
        component: 'TextBlock',
        content: 'This is a text block',
        editor: true,
    },
    {
        uid: null,
        name: 'Header',
        icon: 'bi bi-type-h1',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Background: "",
          Color: "",
          Align: 'left',
          FontSize: null,
          FontSizeType: { name: 'rem', code: 'rem' },      
          LineHeight: null,
          LineHeightType: { name: 'rem', code: 'rem' },              
        },
        component: 'HeaderBlock',
        content: 'This is a header block',
        editor: false,
        style: 'h1',
    },
    {
        uid: null,
        name: 'Columns',
        icon: 'bi bi-layout-three-columns',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Background: "",
        },
        component: 'ColumnBlock',
        columns: [],
        columnsCount: 2,
        alignVertical: 'start',
    },
    {
        uid: null,
        name: 'Section',
        icon: 'bi bi-aspect-ratio',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Background: "",
          Container: false,
        },
        component: 'SectionBlock',
        blocks: [],
    },
    {
        uid: null,
        name: 'Image',
        icon: 'bi bi-image',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Background: "",
          Align: 'left',
          Width: '100',
          WidthType: { name: '%', code: '%' },
        },
        component: 'ImageBlock',
        src: 'https://neonet.id/assets/images/slider/default.jpg',
    },
    {
        uid: null,
        name: 'Twig Block',
        icon: 'bi bi-braces',
        settings: {
          Padding: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
          Margin: {
            top: null,
            right: null,
            bottom: null,
            left: null,
          },
        },
        component: 'TwigBlock',
        block: "",
    },
    {
      uid: null,
      name: 'Button',
      icon: 'bi bi-link',
      settings: {
        Padding: {
          top: null,
          right: null,
          bottom: null,
          left: null,
        },
        Margin: {
          top: null,
          right: null,
          bottom: null,
          left: null,
        },
        Background: "",
        Color: "",
        Align: 'left',
        FontSize: null,
        FontSizeType: { name: 'rem', code: 'rem' },          
      },
      component: 'ButtonBlock',
      label: 'Some text',
      link: '#',
      target: '_self',
      buttonclass: '',
    },    
    {
      uid: null,
      name: 'Code',
      icon: 'bi bi-code-slash',
      settings: {
        Padding: {
          top: null,
          right: null,
          bottom: null,
          left: null,
        },
        Margin: {
          top: null,
          right: null,
          bottom: null,
          left: null,
        },
        Background: "",
        Color: "",
        Align: 'left',
      },
      component: 'CodeBlock',
      code: "",
    },    
  ],
})